### ISSUE TITLE
Can't compile because of the following error

### ISSUE THREAD

**Issue by joviledog** [timboudreau/acteur#5]
Non-resolvable parent POM for com.mastfrog:acteur-parent:[unknown-version]: Failure to find com.mastfrog:mastfrog-parent:pom:1.6.5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ com.mastfrog:acteur-parent:[unknown-version], C:\Users\Andy\Source\Repos\acteur\pom.xml, line 5, column 13 -> [Help 2]
[ERROR]

**Comment by timboudreau** [comment]
I should add a &lt;`repositories`&gt; section to the pom.xml for acteur-parent - that's what's missing.

Two options to quickly get going, since I won't have a chance to fix this for a few days:

1.  Build acteur and all it's dependencies by building [this project](https://github.com/timboudreau/mastfrog-parent) which imports acteur as a git submodule, and contains the missing parent pom (hint: check out mastfrog-parent and run the `init` script in the root to check out all the submodules and build the parent pom), *or*

2.  Manually add a &lt;`repositories`&gt; section as described [here](https://timboudreau.com/builds) if you want to get the dependencies from my maven repo instead of building them yourself.

Which one is right depends on what you're trying to do - if you're building acteur, you probably want to build the libraries it uses as well - and there are also a number of helpful libraries that build on acteur there - Guicified JDBC, acteur support for MongoDB that makes specific kinds of things really simple, authentication support and a framework for doing OAuth with it, etc.

**Comment by joviledog** [comment]
I used option #2 above and it could compile now.  My purpose is to experience the mongodb.async.acteurAsyncTest.  Then I might try to learn acteur framework.  Is there a tutorial guide on how to install this framework?

**Comment by timboudreau** [comment]
Hmm, what's interesting about that test?

There are some guides in the [blogs I wrote](https://timboudreau.com/blog/updatedActeur/read) when it was first released, and a tutorial on the site.

To use the framework, just declare a dependency on it and start it.  I was going after the user experience of nodejs - no giant appservers, just a framework that lets you compose low-footprint, incredibly scalable web applications.  For a small example application, check out [tiny-maven-proxy](https://github.com/timboudreau/tiny-maven-proxy) - some of the code is a little complex because I have it serve files in small chunks, so it can run in a 8Mb footprint and serve multiple users.  But it shows how a bunch of things are done.
